# -*- coding: utf-8 -*-
"""Teoria_Ap_estatistico_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-jCoyEynhCgyj8Vrw-jt09UMTdvbxf6

# Regras do Collab
Caso prefecise usar o dataset, baixar o mesmo no colab a aba arquivos

Quando editar uma parte do codigo crie uma nova celula se identificando e tambem a data que foi feito o algoritmo.
"""

#Intaladores de pacotes
install.packages("fitdistrplus")
install.packages("dplyr")
install.packages("knitr")
install.packages("kableExtra")

# Lista de arquivos que estão neste colab junto com as bibliotecas

library(fitdistrplus)
library(knitr)
library(kableExtra)
library(dplyr)


list.files()

"""Metricas estatisticas das variaveis qualitativas"""

#Metricas estatisticas

dados <- read.csv("Santos2018_2025.csv")

tempo_num <- as.numeric(dados$tempo_total_atracacao)


media <- mean(tempo_num)
mediana <- median(tempo_num)
moda <- as.numeric(names(tempo_num)[tempo_num == max(tempo_num)])
variancia <- var(tempo_num)
desvio_padrao <- sd(tempo_num)
mediana_geometrica <- exp(mean(log(tempo_num)))
desvio_absoluto <- mean(abs(tempo_num - mean(tempo_num)))
MAD <- mad(tempo_num, constant = 1)
amplitude <- diff(range(tempo_num))

print("tempo total da experiencia do navio no porto de Santos")

# Mostrar resultados
paste("Média = ", round(media, digits = 2))
paste("Mediana = ", round(mediana, digits = 2))
paste("Variância = ", round(variancia, digits = 2))
paste("Desvio Padrão = ", round(desvio_padrao, digits = 2))
paste("Mediana Geometrica = ", round(mediana_geometrica,digits = 2))
paste("Desvio Absoluto Médio = ", round(desvio_absoluto, digits = 2))
paste("MAD = ", round(MAD, digits = 2))
paste("Amplitude = ", round(amplitude, digits = 2))
paste("1 Quartil = ", round(quantile(tempo_num, probs = 0.25), digits = 2))
paste("2 Quartil = ", round(quantile(tempo_num, probs = 0.50), digits = 2))
paste("3 Quartil = ", round(quantile(tempo_num, probs = 0.75), digits = 2))
paste("4 Quartil = ", round((quantile(tempo_num, probs = 1)), digits = 2))
paste("Amplitude Interquartilica = ", round(IQR(tempo_num), digits = 2))

print("tempo da operacão")

tempo_op <- as.numeric(dados$tempo_operacao)


media <- mean(tempo_op)
mediana <- median(tempo_op)
moda <- as.numeric(names(tempo_op)[tempo_op == max(tempo_op)])
variancia <- var(tempo_op)
desvio_padrao <- sd(tempo_op)
mediana_geometrica <- exp(mean(log(tempo_op)))
desvio_absoluto <- mean(abs(tempo_op - mean(tempo_op)))
MAD <- mad(tempo_op, constant = 1)
amplitude <- diff(range(tempo_op))


# Mostrar resultados
paste("Média = ", round(media, digits = 2))
paste("Mediana = ", round(mediana, digits = 2))
paste("Variância = ", round(variancia, digits = 2))
paste("Desvio Padrão = ", round(desvio_padrao, digits = 2))
paste("Mediana Geometrica = ", round(mediana_geometrica,digits = 2))
paste("Desvio Absoluto Médio = ", round(desvio_absoluto, digits = 2))
paste("MAD = ", round(MAD, digits = 2))
paste("Amplitude = ", round(amplitude, digits = 2))
paste("1 Quartil = ", round(quantile(tempo_num, probs = 0.25), digits = 2))
paste("2 Quartil = ", round(quantile(tempo_num, probs = 0.50), digits = 2))
paste("3 Quartil = ", round(quantile(tempo_num, probs = 0.75), digits = 2))
paste("4 Quartil = ", round((quantile(tempo_num, probs = 1)), digits = 2))
paste("Amplitude Interquartilica = ", round(IQR(tempo_num), digits = 2))

print("tempo da espera")

tempo_ex <- as.numeric(dados$tempo_espera)


media <- mean(tempo_ex)
mediana <- median(tempo_ex)
moda <- as.numeric(names(tempo_ex)[tempo_ex == max(tempo_ex)])
variancia <- var(tempo_ex)
desvio_padrao <- sd(tempo_ex)
mediana_geometrica <- exp(mean(log(tempo_ex)))
desvio_absoluto <- mean(abs(tempo_ex - mean(tempo_ex)))
MAD <- mad(tempo_ex, constant = 1)
amplitude <- diff(range(tempo_ex))


# Mostrar resultados
paste("Média = ", round(media, digits = 2))
paste("Mediana = ", round(mediana, digits = 2))
paste("Variância = ", round(variancia, digits = 2))
paste("Desvio Padrão = ", round(desvio_padrao, digits = 2))
paste("Mediana Geometrica = ", round(mediana_geometrica,digits = 2))
paste("Desvio Absoluto Médio = ", round(desvio_absoluto, digits = 2))
paste("MAD = ", round(MAD, digits = 2))
paste("Amplitude = ", round(amplitude, digits = 2))
paste("1 Quartil = ", round(quantile(tempo_num, probs = 0.25), digits = 2))
paste("2 Quartil = ", round(quantile(tempo_num, probs = 0.50), digits = 2))
paste("3 Quartil = ", round(quantile(tempo_num, probs = 0.75), digits = 2))
paste("4 Quartil = ", round((quantile(tempo_num, probs = 1)), digits = 2))
paste("Amplitude Interquartilica = ", round(IQR(tempo_num), digits = 2))

print("tempo de Permanencia")

tempo_pe <- as.numeric(dados$tempo_permanencia)


media <- mean(tempo_pe)
mediana <- median(tempo_pe)
moda <- as.numeric(names(tempo_pe)[tempo_pe == max(tempo_pe)])
variancia <- var(tempo_pe)
desvio_padrao <- sd(tempo_pe)
mediana_geometrica <- exp(mean(log(tempo_pe)))
desvio_absoluto <- mean(abs(tempo_pe - mean(tempo_pe)))
MAD <- mad(tempo_pe, constant = 1)
amplitude <- diff(range(tempo_pe))


# Mostrar resultados
paste("Média = ", round(media, digits = 2))
paste("Mediana = ", round(mediana, digits = 2))
paste("Variância = ", round(variancia, digits = 2))
paste("Desvio Padrão = ", round(desvio_padrao, digits = 2))
paste("Mediana Geometrica = ", round(mediana_geometrica,digits = 2))
paste("Desvio Absoluto Médio = ", round(desvio_absoluto, digits = 2))
paste("MAD = ", round(MAD, digits = 2))
paste("Amplitude = ", round(amplitude, digits = 2))
paste("1 Quartil = ", round(quantile(tempo_num, probs = 0.25), digits = 2))
paste("2 Quartil = ", round(quantile(tempo_num, probs = 0.50), digits = 2))
paste("3 Quartil = ", round(quantile(tempo_num, probs = 0.75), digits = 2))
paste("4 Quartil = ", round((quantile(tempo_num, probs = 1)), digits = 2))
paste("Amplitude Interquartilica = ", round(IQR(tempo_num), digits = 2))

"""Tratamento dos Dados"""

#Tratamento de dados

dados <- dados %>%
  mutate(
    berco = as.factor(berco),
    terminal = as.factor(terminal),
    mes = as.factor(mes)
  )

dados <- dados %>%
  mutate(
    log_tempo_espera = log(tempo_espera + 1),
    log_tempo_permanencia = log(tempo_permanencia),
    log_tempo_operacao = log(tempo_operacao),
    log_tempo_total_navio = log(tempo_total_atracacao)
  )

breaks_espera <- quantile(dados$log_tempo_espera, probs = seq(0,1,0.25), na.rm = TRUE)

dados$faixa_espera <- cut(dados$log_tempo_espera,
                       breaks = breaks_espera,
                       include.lowest = TRUE,
                       labels = c("baixa","media","alta","critica"))

dados <- dados %>%
  mutate(
    eficiencia = tempo_operacao / tempo_total_atracacao
  )

breaks_ef <- quantile(dados$eficiencia, probs = seq(0,1,0.25), na.rm = TRUE)

dados$faixa_eficiencia <- cut(dados$eficiencia,
                           breaks = breaks_ef,
                           include.lowest = TRUE,
                           labels = c("baixa","media","alta","otima"))

dados <- dados %>%
  mutate(
    berco = as.factor(berco),
    terminal = as.factor(terminal),
    mes = as.factor(mes)
  )

"""Informações Dataset"""

# Informações do dataset
str(dados)
cat(paste("\nNome das colunas ", "\n"))
colnames(dados)

"""Fatores e tanbles das Variaveis"""

# Factores das variaveis

print("meses")
table(factor(dados$mes, levels = c("jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez")))

table(as.numeric(factor(dados$mes, levels = c("jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez"))))

print("Anos")
table(dados$ano)


print("tipo de navegacao")

table(dados$tipo_de_navegacao_da_atracacao)

print("Tipo Operacao")

table(dados$tipo_de_operacao )

print("berco")

table(dados$idberco)

"""Boxplots para a analise da assimetria"""

# Box plot unico

# Box plot do periodo de navio que ficou atracado no Porto

boxplot(tempo_num,
        outline = FALSE,
        main = "Periodo do total do navio no porto",
        ylab = "valores",
        col = "lightblue",
        border = "darkblue",
        notch = F
        )

boxplot(tempo_op,
        outline = FALSE,
        main = "Periodo do total da operação no porto",
        ylab = "valores",
        col = "lightblue",
        border = "darkblue",
        notch = F
        )

boxplot(tempo_pe,
        outline = FALSE,
        main = "Periodo do permanencia do navio no porto",
        ylab = "valores",
        col = "lightblue",
        border = "darkblue",
        notch = F
        )

boxplot(tempo_ex,
        outline = FALSE,
        main = "Periodo de espera do navio no porto",
        ylab = "valores",
        col = "lightblue",
        border = "darkblue",
        notch = F
        )

"""Histograma da variavel qualitativa meses"""

# Histogramas e analise da distribuição
meses <- as.numeric(factor(dados$mes, levels = c("jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez")))

hist(meses,
     breaks = seq(0.5, 12.5, by = 1),
     right = TRUE,
     col = "lightgreen",
     main = "Histograma dos Meses (convertido)",
     xlab = "Meses (1-12)")

"""Histogramas para a analise das distribuições nos tempos de atracação"""

#Histograma dos tempos de atracacao e operacao

hist(dados$log_tempo_permanencia,
     breaks = "FD",
     main = "Histograma (escala log) do tempo de permanencia",
     col = "lightblue",
     xlab = "log(Tempo)",
     ylab = "Frequência")

    hist(log(dados$tempo_operacao),
     breaks = "FD",
     main = "Histograma (escala log) do tempo de operação",
     col = "lightblue",
     xlab = "log(Tempo)",
     ylab = "Frequência")

    hist(log(dados$tempo_espera),
    breaks = "FD",
     main = "Histograma (escala log) do tempo de espera",
     col = "lightblue",
     xlab = "log(Tempo)",
     ylab = "Frequência")

    hist(log(dados$tempo_total_atracacao),
     breaks = "FD",
     main = "Histograma (escala log) do tempo total da atracação",
     col = "lightblue",
     xlab = "log(Tempo)",
     ylab = "Frequência")

"""Validação das distribuições das variaveis de tempo analisadas, usando o coeficiente de variação"""

# Variabilidade dos dados

permanencia <- dados$tempo_permanencia

espera <- dados$tempo_espera

total <- dados$tempo_total_atracacao

operacao <- dados$tempo_operacao

paste("variabilidade do Tempo de permanencia ", sd(permanencia)/ mean(permanencia))

paste("variabilidade do Tempo de espera ", sd(espera)/ mean(espera))

paste("variabilidade do Tempo de total da atracação ", sd(total)/ mean(total))

paste("variabilidade do Tempo de total da operação ", sd(operacao)/ mean(operacao))

"""Tipos de distribuições possiveis para as variaveis estudadas de tempo"""

# Tipos de distribuição usados para comparação

dates <- rnorm(100, mean = 5, sd = 0.5)

plot(fitdist(dates, "norm"))

dates <- rlnorm(100, mean = 10, sd = 1)

plot(fitdist(dates, "lnorm"))

dates <- rexp(100, rate = 0.5)

plot(fitdist(dates, "exp"))

dates <- rgamma(100, shape = 3 ,rate = 0.5)

plot(fitdist(dates, "gamma"))

"""Graficos de colunas dos tempos totais de operação e os tempos de permanencia dos navios no Porto de Santos mensais e anuais"""

# Graficos de barras dos anos e dos meses baseado na soma do tempo de atracação:

mes <- factor(dados$mes, levels = c("jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez"))

tempo_meses_at <- tapply(dados$tempo_permanencia, mes, sum)

tempo_anos_at <- tapply(dados$tempo_permanencia, dados$ano, sum)

tempo_meses_op <- tapply(dados$tempo_operacao, mes, sum)

tempo_anos_op <- tapply(dados$tempo_operacao, dados$ano, sum)

barplot(tempo_anos_at,
        col = "lightblue",
        main = "Total do tempo de atracação por anos",
        xlab = "Anos",
        ylab = "Tempo em Horas"
)

barplot(tempo_anos_op,
        col = "lightgreen",
        main = "Total do tempo de operação por anos",
        xlab = "Anos",
        ylab = "Tempo em Horas"
)

barplot(tempo_meses_at,
        col = "lightblue",
        main = "Total do tempo de atracação por meses",
        xlab = "Mês",
        ylab = "Tempo em Horas"
)

barplot(tempo_meses_op,
        col = "lightgreen",
        main = "Total do tempo de operação por meses",
        xlab = "Mês",
        ylab = "Tempo em Horas"
)

# Graficos de barras dos anos e dos meses baseado na média tempo de atracação:

tempo_meses_at <- tapply(dados$tempo_permanencia, dados$ano, mean)

tempo_anos_at <- tapply(dados$tempo_permanencia, dados$ano, mean)

tempo_meses_op <- tapply(dados$tempo_operacao, meses, mean)

tempo_anos_op <- tapply(dados$tempo_operacao, dados$ano, mean)

barplot(tempo_anos_at,
        col = "lightblue",
        main = "Média do tempo de atracação por anos",
        xlab = "Anos",
        ylab = "Tempo em Horas"
)

barplot(tempo_anos_op,
        col = "lightgreen",
        main = "Média do tempo de operação por anos",
        xlab = "Anos",
        ylab = "Tempo em Horas"
)

barplot(tempo_meses_at,
        col = "lightblue",
        main = "Média do tempo de atracação por meses",
        xlab = "Mês",
        ylab = "Tempo em Horas"
)


barplot(tempo_meses_op,
        col = "lightgreen",
        main = "Média do tempo de operação por meses",
        xlab = "Mês",
        ylab = "Tempo em Horas"
)

"""Tabelas de Dupla entrada sobre os terminais e os meses sobre a faixa de eficiencia no porto junto com os qui-quadrados de Pearson"""

# tabela de dupla entrada:


print("Tabela de dupla entrada entre terminal e faixa de espera")
tab_te <- table(dados$terminal, dados$faixa_espera)

tab_freq_te <- rbind(
  cbind(tab_te, margin.table(tab_te,1)),
  c(margin.table(tab_te,2), sum(margin.table(tab_te,1)))
)

dimnames(tab_freq_te)[[1]][4]
dimnames(tab_freq_te)[[2]][4]

kable(tab_freq_te)

chisq.test(tab_te)


print("Tabela de dupla entrada entre meses e faixa de espera")

tab_me <- table(mes, dados$faixa_espera)

tab_freq_me <- rbind(
  cbind(tab_me, margin.table(tab_me,1)),
  c(margin.table(tab_me,2), sum(margin.table(tab_me,1)))
)

dimnames(tab_freq_me)[[1]][4]
dimnames(tab_freq_me)[[2]][4]

kable(tab_freq_me)

chisq.test(tab_me)

print("Tabela de dupla entrada entre terminal e faixa de eficiencia")

tab_eff <- table(dados$terminal, dados$faixa_eficiencia)

tab_freq_eff <- rbind(
  cbind(tab_eff, margin.table(tab_eff,1)),
  c(margin.table(tab_eff,2), sum(margin.table(tab_eff,1)))
)

dimnames(tab_freq_eff)[[1]][4]
dimnames(tab_freq_eff)[[2]][4]

kable(tab_freq_eff)

chisq.test(tab_eff)

print("Tabela de dupla entrada entre meses e faixa de eficiencia")

tab_mf <- table(mes, dados$faixa_eficiencia)

tab_freq_mf <- rbind(
  cbind(tab_mf, margin.table(tab_mf,1)),
  c(margin.table(tab_mf,2), sum(margin.table(tab_mf,1)))
)

dimnames(tab_freq_mf)[[1]][4]
dimnames(tab_freq_mf)[[2]][4]

kable(tab_freq_mf)

chisq.test(tab_mf)

print("Tabela de dupla entrada entre berço e faixa de eficiencia")

tab_bf <- table(dados$berco, dados$faixa_eficiencia)

tab_freq_bf <- rbind(
  cbind(tab_bf, margin.table(tab_bf,1)),
  c(margin.table(tab_bf,2), sum(margin.table(tab_bf,1)))
)

dimnames(tab_freq_bf)[[1]][4]
dimnames(tab_freq_bf)[[2]][4]

kable(tab_freq_bf)

chisq.test(tab_bf)

print("Tabela de dupla entrada entre berço e faixa de espera")

tab_be <- table(dados$berco, dados$faixa_espera)

tab_freq_be <- rbind(
  cbind(tab_be, margin.table(tab_be,1)),
  c(margin.table(tab_be,2), sum(margin.table(tab_be,1)))
)

dimnames(tab_freq_be)[[1]][4]
dimnames(tab_freq_be)[[2]][4]

kable(tab_freq_be)

chisq.test(tab_be)

"""Correlações entre as variaveis temporais estudadas com log junto com os devidos testes entre elas"""

#correlações

vars_log <- dados %>%
  select(log_tempo_espera,
         log_tempo_operacao,
         log_tempo_permanencia,
         log_tempo_total_navio)

cor_mat <- cor(vars_log, use = "complete.obs")

kable(round(cor_mat, 2), caption = "Correlação (escala log)")

cor.test(dados$log_tempo_espera, dados$log_tempo_operacao)
cor.test(dados$log_tempo_espera, dados$log_tempo_permanencia)
cor.test(dados$log_tempo_espera, dados$log_tempo_total_navio)

cor.test(dados$log_tempo_operacao, dados$log_tempo_permanencia)
cor.test(dados$log_tempo_operacao, dados$log_tempo_total_navio)

cor.test(dados$log_tempo_permanencia, dados$log_tempo_total_navio)

"""Correlações entre as variaveis temporais estudadas sem log junto com os devidos testes entre elas"""

vars <- dados %>%
  select(tempo_espera,
         tempo_operacao,
         tempo_permanencia,
         tempo_total_atracacao)

cor_mat <- cor(vars, use = "complete.obs")

kable(round(cor_mat, 2), caption = "Correlação (escala sem log)")

cor.test(dados$tempo_espera, dados$tempo_operacao)
cor.test(dados$tempo_espera, dados$tempo_permanencia)
cor.test(dados$tempo_espera, dados$tempo_total_atracacao)

cor.test(dados$tempo_operacao, dados$tempo_permanencia)
cor.test(dados$tempo_operacao, dados$tempo_total_atracacao)

cor.test(dados$tempo_permanencia, dados$tempo_total_atracacao)

"""Sumario dos dos terminais sobre o tempo de espera"""

tapply(dados$log_tempo_espera, dados$terminal, summary)

"""Sumario dos dos terminais sobre o tempo de espera"""

tapply(dados$log_tempo_espera, dados$berco, summary)

"""boxplot comparativos dos tempos estudados com log sobre os meses



"""

boxplot(dados$log_tempo_espera ~ mes,
        col = "darkblue",
        border = "grey",
        main = "Distribuição dos tempo de espera (com log) por mes",
        xlab = "terminal",
        ylab = "tempo de espera",
        outline = FALSE
        )

boxplot(dados$log_tempo_operacao ~ mes,
        col = "darkblue",
        border = "grey",
        main = "Distribuição dos tempo de operação (com log) por mes",
        xlab = "terminal",
        ylab = "tempo de espera",
        outline = FALSE
        )

boxplot(dados$log_tempo_permanencia ~ mes,
        col = "darkblue",
        border = "grey",
        main = "Distribuição dos tempo de permanencia (com log) por mes",
        xlab = "terminal",
        ylab = "tempo de espera",
        outline = FALSE
        )

boxplot(dados$log_tempo_total_navio ~ mes,
        col = "darkblue",
        border = "grey",
        main = "Distribuição do tempo total do navio (com log) por mes",
        xlab = "terminal",
        ylab = "tempo de espera",
        outline = FALSE
        )

"""Graficos de Diperção entre as variaveis temporais (com log)"""

#Grafico de disperção

plot(dados$log_tempo_espera, dados$log_tempo_total_navio,
     main = "Tempo de Espera vs Tempo Total do Navio",
     xlab = "log tempo de espera",
     ylab = "log tempo total de navio")

plot(dados$log_tempo_espera, dados$log_tempo_operacao,
     main = "Tempo de Espera vs Tempo total da operacao",
     xlab = "log tempo de espera",
     ylab = "log tempo de operação")

plot(dados$log_tempo_espera, dados$log_tempo_permanencia,
     main = "Tempo de Espera vs Tempo de permanecia do Navio",
     xlab = "log tempo de espera",
     ylab = "log tempo de permanencia")

plot(dados$log_tempo_operacao, dados$log_tempo_total_navio,
     main = "Tempo de operacao vs Tempo Total do Navio",
     xlab = "log tempo da operação",
     ylab = "log tempo total de navio")

plot(dados$log_tempo_operacao, dados$log_tempo_permanencia,
     main = "Tempo de operacao vs Tempo Permanencia do Navio",
     xlab = "log tempo da operação",
     ylab = "log tempo da pemanencia do navio")

plot(dados$log_tempo_permanencia, dados$log_tempo_total_navio,
     main = "Tempo de permanencia vs Tempo Total do Navio",
     xlab = "log tempo de permanencia do navio",
     ylab = "log tempo total de navio")

"""Graficos de Disperção das variaveis temporais estudadas (sem log)"""

plot(dados$tempo_espera, dados$tempo_total_atracacao,
     main = "Tempo de Espera vs Tempo Total do Navio",
     xlab = "tempo de espera",
     ylab = "tempo total de navio")

plot(dados$tempo_espera, dados$tempo_operacao,
     main = "Tempo de Espera vs Tempo total da operacao",
     xlab = "tempo de espera",
     ylab = "tempo de operação")

plot(dados$tempo_espera, dados$tempo_permanencia,
     main = "Tempo de Espera vs Tempo de permanecia do Navio",
     xlab = "tempo de espera",
     ylab = "tempo de permanencia")

plot(dados$tempo_operacao, dados$tempo_total_atracacao,
     main = "Tempo de operacao vs Tempo Total do Navio",
     xlab = "tempo da operação",
     ylab = "tempo total de navio")

plot(dados$tempo_operacao, dados$tempo_permanencia,
     main = "Tempo de operacao vs Tempo Permanencia do Navio",
     xlab = "tempo da operação",
     ylab = "tempo da pemanencia do navio")

plot(dados$tempo_permanencia, dados$tempo_total_atracacao,
     main = "Tempo de permanencia vs Tempo Total do Navio",
     xlab = "tempo de permanencia do navio",
     ylab = "tempo total de navio")

"""Verificação da variavel tempo espera para verificar a presença de valores NA ou Inf + -"""

# Verificação de valores NA ou inf +-

summary(dados$tempo_espera)
summary(dados$log_tempo_espera)

sum(is.na(dados$log_tempo_espera))
sum(is.infinite(dados$log_tempo_espera))